version: 2
multi-ecosystem-groups:
  tauri:
    schedule:
      interval: weekly
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 1
    patterns:
    - "@tauri-apps/*"
    multi-ecosystem-group: tauri
  - package-ecosystem: cargo
    directory: /src-tauri
    schedule:
      interval: weekly
    cooldown:
      default-days: 1
    patterns:
    - tauri
    - tauri-*
    multi-ecosystem-group: tauri
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
